CREATE DATABASE SQL_ASSIGNMENT
USE SQL_ASSIGNMENT;

DROP TABLE A;
CREATE TABLE A(EMP_ID VARCHAR(20), 
EMP_NAME VARCHAR(20), EMP_SALARY INT (10),
 EMP_AGE INT (60), EMP_GENDER VARCHAR(20), EMP_DEPT VARCHAR (20));
INSERT INTO A(EMP_ID, EMP_NAME, EMP_SALARY, EMP_AGE,  EMP_GENDER,EMP_DEPT)
VALUES (101, "ROSS", 25000, 28, "MALE", "OPERATIONS"),
(102, "RACHEL", 24000, 26, "FEMALE", "SUPPORT"),
(103, "MONICA", 28000, 26, "FEMALE", "HR"),
(104, "JOEY", 24000, 23, "MALE", "OPERATIONS");
SELECT*FROM A;
DROP TABLE B;
CREATE TABLE B(EMP_ID VARCHAR(20), 
EMP_NAME VARCHAR(20), EMP_SALARY INT (10),
 EMP_AGE INT (60), EMP_GENDER VARCHAR(20), EMP_DEPT VARCHAR (20));
INSERT INTO B(EMP_ID, EMP_NAME, EMP_SALARY, EMP_AGE,  EMP_GENDER,EMP_DEPT)
VALUES (101, "GINNI", 28000, 21, "FEMALE", "OPERATIONS"),
(102, "GEORGIA", 32000, 26, "FEMALE", "SUPPORT"),
(103, "PAUL", 28000, 26, "MALE", "ANALYTICS"),
(104, "AUSTIN", 23000, 22, "MALE", "OPERATIONS");

SELECT*FROM B;

# RIGHT JOIN
SELECT A.EMP_ID, A.EMP_NAME, A.EMP_SALARY, 
A.EMP_AGE, A.EMP_GENDER, A.EMP_DEPT,   
B.EMP_ID, B.EMP_NAME,
 B.EMP_GENDER
FROM A RIGHT JOIN B ON A.EMP_dept=B.EMP_dept; 
# LEFT JOIN
SELECT A.EMP_ID, A.EMP_NAME, A.EMP_SALARY, 
A.EMP_AGE, A.EMP_GENDER, A.EMP_DEPT,   
B.EMP_ID, B.EMP_NAME,
 B.EMP_GENDER
FROM A LEFT JOIN B ON A.EMP_SALARY=B.EMP_SALARY; 
SELECT A.EMP_ID, A.EMP_NAME, A.EMP_SALARY, 
A.EMP_AGE, A.EMP_GENDER, A.EMP_DEPT,   
B.EMP_ID, B.EMP_NAME,
 B.EMP_GENDER
FROM B INNER JOIN A ON B.EMP_dept=A.EMP_dept; 
#2 
SELECT A.EMP_ID, A.EMP_NAME, A.EMP_SALARY, 
A.EMP_AGE, A.EMP_GENDER, A.EMP_DEPT,   
B.EMP_ID, B.EMP_NAME,
 B.EMP_GENDER
FROM B INNER JOIN A ON B.EMP_AGE > A.EMP_AGE; 

#INTERSECT
SELECT * FROM A where A.EMP_AGE in (select B.EMP_AGE from B);
SELECT * FROM A where A.EMP_SALARY in (select B.EMP_SALARY from B);

#UNION

SELECT A.EMP_ID, A.EMP_NAME, A.EMP_SALARY, 
A.EMP_AGE, A.EMP_GENDER, A.EMP_DEPT FROM A
UNION   
SELECT B.EMP_ID, B.EMP_NAME, B.EMP_SALARY, 
B.EMP_AGE, B.EMP_GENDER, B.EMP_DEPT FROM B;

SELECT A.EMP_ID, A.EMP_NAME, A.EMP_SALARY, 
A.EMP_AGE, A.EMP_GENDER, A.EMP_DEPT FROM A
UNION ALL 
SELECT B.EMP_ID, B.EMP_NAME, B.EMP_SALARY, 
B.EMP_AGE, B.EMP_GENDER, B.EMP_DEPT FROM B;


